{{- if .Values.serviceMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "kube-eagle.name" . }}
    chart: {{ template "kube-eagle.chart" . }}
    release: {{ if .Values.serviceMonitor.additionalLabels -}}
      {{- .Release.Name -}}
    {{- else -}}
      {{- .Values.serviceMonitor.releaseLabel -}}
    {{- end }}
    heritage: {{ .Release.Service }}
{{- if .Values.serviceMonitor.additionalLabels }}
{{ toYaml .Values.serviceMonitor.additionalLabels | indent 4 }}
{{- end -}}
  name: {{ template "kube-eagle.fullname" . }}
spec:
  endpoints:
  - interval: {{ .Values.serviceMonitor.interval }}
    port: http
    path: /metrics
    scrapeTimeout: {{ .Values.serviceMonitor.interval }}
  selector:
    matchLabels:
      app: {{ template "kube-eagle.name" . }}
{{- end }}